version: '3.5'

services:
  db:
    image: mongo:5.0.2
    environment:
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
     - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    expose:
      - 27017
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./database:/data/db

  web:
    image: drakkarsoftware/errors.octobot.online
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - MONGODB_URI=${MONGO_URI}
      - PORT=${PORT}
    links:
      - db
    expose:
      - 8080
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
